{% set name = "delocate" %}
{% set version = "0.10.0" %}
{% set sha256 = "e677a0d4ba93e8b95aa523253b331eda3149c4bd169f813d9ce0e2e75784b375" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  skip: true  # [not osx]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - six
    - wheel

test:
  imports:
    - delocate
  commands:
    - delocate-listdeps -h
    - delocate-wheel -h

about:
  home: https://github.com/matthew-brett/delocate
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Move OSX dynamic libraries into package
